# Generated by Django 3.1.3 on 2021-07-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockDataAnalysisApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GainerStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbols', models.CharField(max_length=10)),
                ('Names', models.CharField(max_length=100)),
                ('Prices', models.CharField(max_length=30)),
                ('Changes', models.CharField(max_length=10)),
                ('PercentageChanges', models.CharField(max_length=10)),
                ('MarketCap', models.CharField(max_length=30)),
                ('AverageVolume', models.CharField(max_length=30)),
                ('Volume', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LoserStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbols', models.CharField(max_length=10)),
                ('Names', models.CharField(max_length=100)),
                ('Prices', models.CharField(max_length=30)),
                ('Changes', models.CharField(max_length=10)),
                ('PercentageChanges', models.CharField(max_length=10)),
                ('MarketCap', models.CharField(max_length=30)),
                ('AverageVolume', models.CharField(max_length=30)),
                ('Volume', models.CharField(max_length=30)),
            ],
        ),
    ]
